---
- hosts: 34.226.208.71
  become: yes
  tasks:
  - name: i want to execute linux command
    command: hostname -i
    register: myresult
    

  - name: i want to display my first result
    debug:
      msg: {{myresult}}
