---
- hosts: 192.168.1.10
  become: yes
  tasks:
  - include_tasks: myfile.yml
  - name: i want to install java
    apt:
     name: apache2
     state: present

  - name: i want to create a folder
    file:
      path: /home/maha/myfolder
      state: directory

  