---
- hosts: 192.168.1.10
  become: yes
  tasks:
  - include_tasks: myfile.yml
  - name: i want to install java
    apt:
     name: apache2
     state: present

  - name: i want to create a folder
    file:
      path: /home/maha/myfolder
      state: directory

  - name: copy a file into a folder in node
    copy:
      src: mytextfille
      dest: /home/maha/myfolder

  - name: how to download any internet file
    get_url:
      url: https://github.com/banabiharisingh/myAnsible/archive/refs/heads/main.zip
      dest: /home/maha/myfolder/
      force_basic_auth: yes

  - name: i want to copy index file into node side
    templates:
      src: myindex.j2
      dest: /var/www/html/index.html



  